#include<stdio.h>
#include<omp.h>
int fib(int n)
{
    int i,j;

    if(n<2)
        return n;
    else{
        #pragma omp task shared(i)//visible to all threads simul. 
        i=fib(n-1);
        #pragma omp task shared(j)
        j=fib(n-2);
        #pragma omp taskwait//wait for child tasks to be completed, generated by current task
        return i+j;
    }
}
int main()
{
    for(int i=1;i<=10;i++)
    {
        printf("%d\n",fib(i));
    }
    
}